name: Playwright Tests
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
env:
  MODE: standalone
  KETCHER_URL: http://localhost:4002
jobs:
  playwright_tests:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Install dependencies
        run: npm ci
      - name: Build all packages
        run: npm run buildCi
      - name: Run example in standalone mode
        run: cd example/ && nohup npm run serve:standalone &
      - name: Install playwright browsers and playwright/test
        run: cd ketcher-autotests/ && npx playwright install --with-deps && npm install -D @playwright/test
      - name: Run playwright tests
        run: cd ketcher-autotests/ && npm run test:ci
      - uses: actions/upload-artifact@v3
        # run even if previous steps fails
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
