name: Playwright Tests
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Install dependencies
        run: npm ci
      - name: Run Build for all packages
        run: npm run build
      - name: Run example in standalone mode
        run: cd example/ && nohup npm run serve:standalone &
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        # run even if previous steps fails
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
