name: Playwright Tests
on:
  push:
    branches:
      - master
      - 'release/**'
  pull_request:
    branches:
      - master
      - 'release/**'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.0
      - name: Check npm version
        run: npm -v
      - name: Check node version
        run: node -v
      - name: Install dependencies
        run: npm ci
      - name: Build all packages
        run: npm run buildCi
      - name: Run example in standalone mode
        run: cd example/ && nohup npm run serve:standalone &
      - name: Go to ketcher-autotests and install playwright browsers
        run: cd ketcher-autotests/ && npx playwright install --with-deps
      - name: Run playwright tests
        env:
          MODE: standalone
          KETCHER_URL: http://localhost:4002
        run: npm run test:ci
      - uses: actions/upload-artifact@v3
        # run even if previous steps fails
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
